In [ ]:
%pip install pandas

Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2026.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [ ]:
#pandas

In [ ]:
# install pandas

In [ ]:
import pandas as pd

In [ ]:
s = pd.Series([10,20,30])

In [ ]:
s

0    10
1    20
2    30
dtype: int64

In [ ]:
type(s)

pandas.core.series.Series

In [ ]:
s = pd.Series([10,20,30],index=['a','b','c'])

In [ ]:
s

a    10
b    20
c    30
dtype: int64

In [ ]:
dic1=["name:","Aditi","age:","18","marks:","84.71"]

In [ ]:
dic1

['name:', 'Aditi', 'age:', '18', 'marks:', '84.71']

In [ ]:
s= pd.Series(["name:","Aditi","age:","18","marks:","84.71"])

In [ ]:
s

0     name:
1     Aditi
2      age:
3        18
4    marks:
5     84.71
dtype: object

In [ ]:
s=pd.Series(5,index=[0,1,2,3,4])

In [ ]:
s

0    5
1    5
2    5
3    5
4    5
dtype: int64

In [ ]:
#attributes

In [ ]:
s = pd.Series([10,20,30],index=['a','b','c'])

In [ ]:
s

a    10
b    20
c    30
dtype: int64

In [ ]:
s.values

array([10, 20, 30])

In [ ]:
s.index

Index(['a', 'b', 'c'], dtype='object')

In [ ]:
s.dtype

dtype('int64')

In [ ]:
s.shape

(3,)

In [ ]:
s*2

a    20
b    40
c    60
dtype: int64

In [ ]:
s=pd.Series([10,None,20])

In [ ]:
s

0    10.0
1     NaN
2    20.0
dtype: float64

In [ ]:
s.isnull()

0    False
1     True
2    False
dtype: bool

In [ ]:
s.dropna()

0    10.0
2    20.0
dtype: float64

In [ ]:
s

0    10.0
1     NaN
2    20.0
dtype: float64

In [ ]:
s.fillna(5)

0    10.0
1     5.0
2    20.0
dtype: float64

In [ ]:
s=pd.Series([1,2,2,3,3,3])

In [ ]:
s

0    1
1    2
2    2
3    3
4    3
5    3
dtype: int64

In [ ]:
s.value_counts()

3    3
2    2
1    1
Name: count, dtype: int64

In [ ]:
s=pd.Series([10,20,30,40], index=['a','b','c','d'])

In [ ]:
s

a    10
b    20
c    30
d    40
dtype: int64

In [ ]:
s['a']

np.int64(10)

In [ ]:
data = {
    "Name": ["Aditi", "Rahul", "Priya"],
    "Age": [20, 22, 21],
    "City": ["Mumbai", "Pune", "Delhi"]
}

In [ ]:
df = pd.DataFrame(data)

In [ ]:
print(df)

    Name  Age    City
0  Aditi   20  Mumbai
1  Rahul   22    Pune
2  Priya   21   Delhi

In [ ]:
data1 = {
    "Subject": ["Java", "PYthon", "C++"],
    "Marks": [67,78,98],
    "Grade": ["C", "B", "A"]
}

In [ ]:
data1 = {
    "Subject": ["Java", "PYthon", "C++"],
    "Marks": [67,78,98],
    "Grade": ["C", "B", "A"]
}
df = pd.DataFrame(data1)

In [ ]:
print(df)

  Subject  Marks Grade
0    Java     67     C
1  PYthon     78     B
2     C++     98     A

In [ ]:
df.to_csv('marks_data.csv', index=False)

In [ ]:
df = pd.read_csv("marks_data.csv")

In [ ]:
df

  Subject  Marks Grade
0    Java     67     C
1  PYthon     78     B
2     C++     98     A

In [ ]:
df.tail()

  Subject  Marks Grade
0    Java     67     C
1  PYthon     78     B
2     C++     98     A

In [ ]:
df.head()

  Subject  Marks Grade
0    Java     67     C
1  PYthon     78     B
2     C++     98     A

In [ ]:
df.shape

(3, 3)

In [ ]:
df.columns

Index(['Subject', 'Marks', 'Grade'], dtype='object')

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 3 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Subject  3 non-null      object
 1   Marks    3 non-null      int64
 2   Grade    3 non-null      object
dtypes: int64(1), object(2)
memory usage: 204.0+ bytes

In [ ]:
df.describe()

           Marks
count   3.000000
mean   81.000000
std    15.716234
min    67.000000
25%    72.500000
50%    78.000000
75%    88.000000
max    98.000000

In [ ]:
df.isnull().sum()

Subject    0
Marks      0
Grade      0
dtype: int64

In [ ]:
df=df.drop_duplicates()

In [ ]:
df

  Subject  Marks Grade
0    Java     67     C
1  PYthon     78     B
2     C++     98     A

In [ ]:
df['Marks'] = df['Marks'].astype(float)

In [ ]:
df

  Subject  Marks Grade  Maeks
0    Java   67.0     C   67.0
1  PYthon   78.0     B   78.0
2     C++   98.0     A   98.0

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 4 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Subject  3 non-null      object
 1   Marks    3 non-null      float64
 2   Grade    3 non-null      object
 3   Maeks    3 non-null      float64
dtypes: float64(2), object(2)
memory usage: 228.0+ bytes

In [ ]:
df["Subject"]

0      Java
1    PYthon
2       C++
Name: Subject, dtype: object

In [ ]:
df[["Subject","Grade","Marks"]]

  Subject Grade  Marks
0    Java     C   67.0
1  PYthon     B   78.0
2     C++     A   98.0

In [ ]:
df= df.sort_values(by="Marks", ascending=False)

In [ ]:
df

  Subject  Marks Grade  Maeks
2     C++   98.0     A   98.0
1  PYthon   78.0     B   78.0
0    Java   67.0     C   67.0